### PR TITLE
Add missing streaming features

### PR DESCRIPTION
**Pull request by DamienDeepgram**
Add support for:
- Pause / Resume sending the audio stream to the websocket
  - This is useful to avoid echo while the AI is speaking
- Websocket Message Types:
  - UtteranceEnd
  - SpeechStarted
  - Finalize

### CODE REVIEW

**Comment by tempo-riz** [comment]
Hey @DamienDeepgram thanks for the PR
For the play/pause feature, you should already be able to do this using start/close, (you can call start again after closing)
note: By default, the Deepgram streaming connection will time out if no audio is sent by the client for 12 seconds. 

about the Websocket message type i'm not sure what are the benefits of your changes, can you clarify ?

**Comment by DamienDeepgram** [comment]
> Hey @DamienDeepgram thanks for the PR
> 
> For the play/pause feature, you should already be able to do this using start/close, (you can call start again after closing) note: By default, the Deepgram streaming connection will time out if no audio is sent by the client for 12 seconds.
> 
> about the Websocket message type i'm not sure what are the benefits of your changes, can you clarify ?

This can be used to keep the websocket open by sending it every 10 seconds

https://developers.deepgram.com/docs/keep-alive

For this use case I want to keep the websocket open so that the echo does not get picked up and it only lasts 2-3 seconds so this meets the needs of the other PR that requires this feature

See: https://github.com/BasedHardware/Friend/pull/487#discussion_r1696164209

Closing and Reopening the websocket is overkill to avoid echo transcription and you lose all the word time stamps and it also restarts diarization which is not a desired outcome.

Would be great to add KeepAlive support too tho

We also have a feature matrix here that might be of interest
- https://developers.deepgram.com/docs/sdk-feature-matrix

I recently added a lot of missing features to our Rust SDK 
- https://github.com/deepgram-devs/deepgram-rust-sdk/pull/76

**Comment by tempo-riz** [comment]
Yeah you are right, play pause would be nice thinking about your use case and in general too, but this needs to support using keepalive to cover all use cases.

If you can implement the keepalive part I'll merge the PR + update the package, otherwise just tell me and I'll add it myself when I have some time.

About messages type LGTM :)

Are you working at Deepgram ? If so maybe you could consider mentioning this unofficial dart package somewhere in your docs ?

**Comment by tempo-riz** [comment]
I will add the keep-alive myself after all :)

**Pull request merged**
